apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  namespace: vpc
  # lables of deployment resource
  labels:
    app: mysql
    tier: mysql
    project: expense
spec:
    replicas: 1
    selector:
      matchLabels:
        app: mysql
        tier: mysql
        project: expense 
    template:
      metadata:
        labels:
          app: mysql
          tier: mysql 
          project: expense 
      spec:
        containers:
        - name: nginx
          image: saimaddala/mysql:1.0.0
---
kind: Service
apiVersion: v1
metadata:
  name: mysql
  namespace: vpc 
spec:
  selector: # labels are used as selectors
    app: mysql
    tier: mysql
    project: expense
  ports:
  - protocol: TCP
    port: 3306 # service port
    targetPort: 3306